apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-simple
  namespace: kargo-kustomize
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-simple
  template:
    metadata:
      labels:
        app: guestbook-simple
    spec:
      containers:
      - image: ghcr.io/<user>/guestbook:v0.0.1
        name: guestbook-simple
        ports:
        - containerPort: 3000
          name: http
