apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
  namespace: kargo-kustomize-example
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/reikamoon/guestbook
      discoveryLimit: 5
      imageSelectionStrategy: SemVer