apiVersion: v1
kind: Service
metadata:
  name: kargo-kustomize
spec:
  type: NodePort
  selector:
    app: kargo-kustomize
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 80
    nodePort: placeholder